[package]
name = "oximo-mosek"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "MOSEK backend for oximo"
readme = "README.md"

[features]
benchmark-support = ["dep:rayon"]

[dependencies]
mosek.workspace = true
oximo-expr.workspace = true
oximo-core.workspace = true
oximo-solver.workspace = true
rustc-hash.workspace = true
rayon = { workspace = true, optional = true }

[lints]
workspace = true
